var searchData=
[
  ['tac_20toe_0',['Tac Toe',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'10. Numerical Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md23',1,'11. Obstacles Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md25',1,'12. Infinity Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md9',1,'4. 5×5 Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md11',1,'5. Word Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md13',1,'6. Misère Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md15',1,'7. Diamond Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md17',1,'8. 4×4 Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md19',1,'9. Pyramid Tic-Tac-Toe']]],
  ['tac_20toe_20bonus_1',['Tac Toe Bonus',['../md__r_e_a_d_m_e.html#autotoc_md27',1,'13. Ultimate Tic-Tac-Toe (Bonus)'],['../md__r_e_a_d_m_e.html#autotoc_md29',1,'14. Memory Tic-Tac-Toe (Bonus)']]],
  ['tac_20toe_20variations_20project_2',['🎮 CS213 - Tic-Tac-Toe Variations Project',['../md__r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['three_5fin_5frow_3',['three_in_row',['../class_infinity___board.html#a24cc8879b19abc564e22dd83c9b53366',1,'Infinity_Board::three_in_row()'],['../class_misere___board.html#a36b4923e697ac3379bf18373f012e3af',1,'Misere_Board::three_in_row()']]],
  ['tic_20tac_20toe_4',['Tic Tac Toe',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'10. Numerical Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md23',1,'11. Obstacles Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md25',1,'12. Infinity Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md9',1,'4. 5×5 Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md11',1,'5. Word Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md13',1,'6. Misère Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md15',1,'7. Diamond Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md17',1,'8. 4×4 Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md19',1,'9. Pyramid Tic-Tac-Toe']]],
  ['tic_20tac_20toe_20bonus_5',['Tic Tac Toe Bonus',['../md__r_e_a_d_m_e.html#autotoc_md27',1,'13. Ultimate Tic-Tac-Toe (Bonus)'],['../md__r_e_a_d_m_e.html#autotoc_md29',1,'14. Memory Tic-Tac-Toe (Bonus)']]],
  ['tic_20tac_20toe_20variations_20project_6',['🎮 CS213 - Tic-Tac-Toe Variations Project',['../md__r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['toe_7',['Toe',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'10. Numerical Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md23',1,'11. Obstacles Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md25',1,'12. Infinity Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md9',1,'4. 5×5 Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md11',1,'5. Word Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md13',1,'6. Misère Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md15',1,'7. Diamond Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md17',1,'8. 4×4 Tic-Tac-Toe'],['../md__r_e_a_d_m_e.html#autotoc_md19',1,'9. Pyramid Tic-Tac-Toe']]],
  ['toe_20bonus_8',['Toe Bonus',['../md__r_e_a_d_m_e.html#autotoc_md27',1,'13. Ultimate Tic-Tac-Toe (Bonus)'],['../md__r_e_a_d_m_e.html#autotoc_md29',1,'14. Memory Tic-Tac-Toe (Bonus)']]],
  ['toe_20variations_20project_9',['🎮 CS213 - Tic-Tac-Toe Variations Project',['../md__r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['type_10',['type',['../class_player.html#a81a15b1b507fd5f2157fb15bf0fd283f',1,'Player']]]
];
