var annotated_dup =
[
    [ "Board", "class_board.html", "class_board" ],
    [ "Diamond_Board", "class_diamond___board.html", "class_diamond___board" ],
    [ "Diamond_UI", "class_diamond___u_i.html", "class_diamond___u_i" ],
    [ "FiveByFive_Board", "class_five_by_five___board.html", "class_five_by_five___board" ],
    [ "FiveByFive_UI", "class_five_by_five___u_i.html", "class_five_by_five___u_i" ],
    [ "FourInARow_Board", "class_four_in_a_row___board.html", "class_four_in_a_row___board" ],
    [ "FourInARow_UI", "class_four_in_a_row___u_i.html", "class_four_in_a_row___u_i" ],
    [ "GameManager", "class_game_manager.html", "class_game_manager" ],
    [ "Infinity_Board", "class_infinity___board.html", "class_infinity___board" ],
    [ "Infinity_UI", "class_infinity___u_i.html", "class_infinity___u_i" ],
    [ "Memory_Board", "class_memory___board.html", "class_memory___board" ],
    [ "Memory_UI", "class_memory___u_i.html", "class_memory___u_i" ],
    [ "Misere_Board", "class_misere___board.html", "class_misere___board" ],
    [ "Misere_UI", "class_misere___u_i.html", "class_misere___u_i" ],
    [ "Move", "class_move.html", "class_move" ],
    [ "NumericalUI", "class_numerical_u_i.html", "class_numerical_u_i" ],
    [ "NumericBoard", "class_numeric_board.html", "class_numeric_board" ],
    [ "ObstaclesBoard", "class_obstacles_board.html", "class_obstacles_board" ],
    [ "ObstaclesUI", "class_obstacles_u_i.html", "class_obstacles_u_i" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "Pyramid_Board", "class_pyramid___board.html", "class_pyramid___board" ],
    [ "PyramidUI", "class_pyramid_u_i.html", "class_pyramid_u_i" ],
    [ "SubBoard", "class_sub_board.html", "class_sub_board" ],
    [ "SUS_Board", "class_s_u_s___board.html", "class_s_u_s___board" ],
    [ "SUS_UI", "class_s_u_s___u_i.html", "class_s_u_s___u_i" ],
    [ "UI", "class_u_i.html", "class_u_i" ],
    [ "Ultimate_UI", "class_ultimate___u_i.html", "class_ultimate___u_i" ],
    [ "UltimateBoard", "class_ultimate_board.html", "class_ultimate_board" ],
    [ "WordBoard", "class_word_board.html", "class_word_board" ],
    [ "WordUI", "class_word_u_i.html", "class_word_u_i" ],
    [ "X_O_Board", "class_x___o___board.html", "class_x___o___board" ],
    [ "XO4x4_Board", "class_x_o4x4___board.html", "class_x_o4x4___board" ],
    [ "XO4x4_UI", "class_x_o4x4___u_i.html", "class_x_o4x4___u_i" ],
    [ "XO_UI", "class_x_o___u_i.html", "class_x_o___u_i" ]
];